import 'package:website/items/class_items.dart';

final List<Product> products = [
  //kvennfatnaður:
  Product(
    id: '1',
    name: 'bumb bag',
    color: 'black',
    price: 100,
    imageUrl: 'assets/bag-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'tablet bag',
    color: 'black',
    price: 100,
    imageUrl: 'assets/bag-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'bracelets-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/bracelets-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'earrings-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/earrings-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'gloves-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/gloves-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'gloves-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/gloves-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'gloves-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/gloves-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'gloves-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/gloves-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'hat-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/hat-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'hat-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/hat-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'hat-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/hat-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'hat-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/hat-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'hat-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/hat-5.jpeg',
  ),
  Product(
    id: '1',
    name: 'purse-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/purse-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'purse-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/purse-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-5.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-6.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-7.jpeg',
  ),
  Product(
    id: '1',
    name: 'PW-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PW-8.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-5.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-6.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-7.jpeg',
  ),
  Product(
    id: '1',
    name: 'ShW-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShW-8.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-5.jpeg',
  ),
  Product(
    id: '1',
    name: 'socks-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/socks-6.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-4.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-5.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-6.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-7.jpeg',
  ),
  Product(
    id: '1',
    name: 'SW-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SW-8.jpeg',
  ),
  Product(
    id: '1',
    name: 'UWW-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWW-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'UWW-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWW-2.jpeg',
  ),
  Product(
    id: '1',
    name: 'UWW-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWW-3.jpeg',
  ),
  Product(
    id: '1',
    name: 'wallet-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/wallet-1.jpeg',
  ),
  Product(
    id: '1',
    name: 'wallet-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/wallet-2.jpeg',
  ),

  //Karlfatnaður:
  Product(
    id: '2',
    name: 'PM-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-1.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-2.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-3.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-4.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-5.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-6.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-7.jpeg',
  ),
  Product(
    id: '2',
    name: 'PM-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/PM-8.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-1.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-2.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-3.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-4.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-5.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-6.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-7.jpeg',
  ),
  Product(
    id: '2',
    name: 'ShM-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/ShM-8.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-1.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-2.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-3.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-4.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-5.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-6.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-7',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-7.jpeg',
  ),
  Product(
    id: '2',
    name: 'SM-8',
    color: 'black',
    price: 100,
    imageUrl: 'assets/SM-8.jpeg',
  ),
  Product(
    id: '2',
    name: 'UWM-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWM-1.jpeg',
  ),
  Product(
    id: '2',
    name: 'UWM-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWM-2.jpeg',
  ),
  Product(
    id: '2',
    name: 'UWM-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWM-3.jpeg',
  ),
  Product(
    id: '2',
    name: 'UWM-4',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWM-4.jpeg',
  ),
  Product(
    id: '2',
    name: 'UWM-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/UWM-5.jpeg',
  ),

  //barnafatnaður:
  Product(
    id: '3',
    name: 'CBCozy-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBCozy-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBO-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBO-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBP-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBP-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBS-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBS-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBS-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBS-2.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBS-3',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBS-3.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBS-5',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBS-5.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBS-6',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBS-6.jpeg',
  ),
  Product(
    id: '3',
    name: 'CBShorts-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CBShorts-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CGD-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CGD-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CGD-2',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CGD-2.jpeg',
  ),
  Product(
    id: '3',
    name: 'CGJ-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CGJ-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CGP-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CGP-1.jpeg',
  ),
  Product(
    id: '3',
    name: 'CGS-1',
    color: 'black',
    price: 100,
    imageUrl: 'assets/CGS-1.jpeg',
  ),
];
