import 'package:website/items/class_items.dart';

final List<Product> products = [
  Product(
    id: '1',
    name: 'Skyrta með slaufu',
    color: 'svartur og hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg',
    description: 'Sæt skyrta með doppum.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '1',
    name: 'Síð röndótt skyrta',
    color: 'blár og hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1462637/pexels-photo-1462637.jpeg',
    description: 'Létt skyrta í einföldu sniði.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '1',
    name: 'Blómamynstrað pils',
    color: 'gulur og svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1631181/pexels-photo-1631181.jpeg',
    description: 'Fallegt pils með litríku mynstri.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Litrík skyrta',
    color: 'teal, bleikur og fjólublár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1839904/pexels-photo-1839904.jpeg',
    description: 'Skemmtileg skyrta í björtum litum.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '1',
    name: 'Rifflað pils',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2085118/pexels-photo-2085118.jpeg',
    description: 'Nútímalegt pils sem hentar hversdags og við sérstök tilefni.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Röndóttur bolur',
    color: 'hvítur, svartur og gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1844012/pexels-photo-1844012.jpeg',
    description: 'Fallegur bolur með svörtu og gulu mynstri.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Háhælaðir skór yfir ökkla',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/928000/pexels-photo-928000.jpeg',
    description: 'Snyrtilegir skór, tilvalnir í hvaða tilefni sem er!',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Strigaskór',
    color: 'Bleikt',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/965324/pexels-photo-965324.jpeg',
    description: 'Þægilegir hversdags skór.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Bambus veski',
    color: 'Ljós brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1805412/pexels-photo-1805412.jpeg',
    description: 'Létt og hentugt veski sem andar vel.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Blár flæðandi kjóll',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/904117/pexels-photo-904117.jpeg',
    description: 'Vandaður kjóll sem hentar við ýmis tilefni.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '1',
    name: 'Gallapils með raufum',
    color: 'Blátt',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg',
    description: 'Frjálsleg útivera í gallapilsi.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Hvítir háhælaðir skór',
    color: 'Hvítt',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/949670/pexels-photo-949670.jpeg',
    description: 'Þægilegur skófatnaður til daglegra nota.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Litrík leðurtaska',
    color: 'grænn og rauður',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/932401/pexels-photo-932401.jpeg',
    description: 'Háglæsileg, stílhrein handtaska.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Stutterma- buxur og bolur',
    color: 'hvítur, rauður og svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/975006/pexels-photo-975006.jpeg',
    description: 'Léttur og þægilegur fatnaður með flottu mynstri.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Loðvesti',
    color: 'Dökk blátt',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/247204/pexels-photo-247204.jpeg',
    description: 'Flott vesti sem hægt er að stíla með ýmsu.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Stutterma samfestingur',
    color: 'grátt',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1877736/pexels-photo-1877736.jpeg',
    description: 'Fíngert sett í jakkafata stíl.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Svartur hlýrabolur',
    color: 'Svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1004642/pexels-photo-1004642.jpeg',
    description: 'Einfaldur hlýrabolur sem passar við flestar buxur.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Skyrtu-jakki',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/932417/pexels-photo-932417.jpeg',
    description: 'Fágaður jakki fyrir flott tilefni.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Fóðraður jakki',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/10625395/pexels-photo-10625395.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Frábær í veturinn.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Stuttermabolur',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2608344/pexels-photo-2608344.jpeg',
    description: 'Sætur, hversdagslegur bolur.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Jakkafatasett',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/953266/pexels-photo-953266.jpeg',
    description: 'Jakkafata buxur og vesti, mjög flott sett.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Svart peysusett',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/963696/pexels-photo-963696.jpeg',
    description: 'Mjúkt og notalegt sett.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Gular gallabuxur',
    color: 'gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1857000/pexels-photo-1857000.jpeg',
    description: 'Litríkt og skemmtilegt útlit fyrir vor og sumar.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'cargobuxur',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/3679044/pexels-photo-3679044.jpeg',
    description: 'Töff hönnun fyrir þá sem vilja setja punktinn yfir i-ið.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Prjónuð peysa',
    color: 'bleikur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2269880/pexels-photo-2269880.jpeg',
    description: 'Fersk samsetning fyrir einstök tækifæri.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Casual gallabuxur',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2331101/pexels-photo-2331101.jpeg',
    description: 'Einfalt til hversdagsnota.',
    subcategory: 'buxur',
  ),
  Product(
    id: '1',
    name: 'Kjóll',
    color: 'gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1936850/pexels-photo-1936850.jpeg',
    description: 'Handhægur og flottur kjóll.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '1',
    name: 'Köflóttur frakki',
    color: 'hvítur/svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/936084/pexels-photo-936084.jpeg',
    description: 'Þægilegur í helgarbröltið.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Kjóll með blómamynstri',
    color: 'bleikur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1468379/pexels-photo-1468379.jpeg',
    description: 'Tískulegt fyrir hlýja sumardaga.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '1',
    name: 'Mynstruð slæða',
    color: 'gulur/blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/852860/pexels-photo-852860.jpeg',
    description: 'Rómantískt og náttúrulegt útlit.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Köflóttur kjóll',
    color: 'svartur/hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/859191/pexels-photo-859191.jpeg',
    description: 'Krúttlegur kjóll í fallegu mynstri.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '1',
    name: 'Stuttermabolur með kraga',
    color: 'gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg',
    description: 'Lifandi litur sem poppar upp á útlitið.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Þægileg peysa með kraga',
    color: 'blár/hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/15647635/pexels-photo-15647635/free-photo-of-a-man-in-a-blue-shirt-and-white-pants-is-jumping-on-a-blue-and-white-umbrella.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Nútímaleg peysa sem er auðvelt að para saman við annan fatnað.',
    subcategory: 'peysur',
  ),
  Product(
    id: '1',
    name: 'Vintage jakki',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29864717/pexels-photo-29864717.jpeg',
    description: 'Gamaldags en eins og ekkert annað.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Fóðruð hettupeysa',
    color: 'Hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29852347/pexels-photo-29852347.jpeg',
    description: 'Mjúk og hlý í búðarröltið.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Galla jakki',
    color: 'blár/ljós',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/247298/pexels-photo-247298.jpeg',
    description: 'Léttur og þægilegur jakki sem passar við hvað sem er.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '1',
    name: 'Köflótt skyrta',
    color: 'blár og rauður',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/58592/pexels-photo-58592.jpeg',
    description: 'Þægileg hversdags skyrta.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '1',
    name: 'Svartur neta kjóll',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/956724/pexels-photo-956724.jpeg',
    description: 'Léttur og svalandi fyrir sumarið.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '1',
    name: 'Þægilegir flatbotna skór með opna tá',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/346751/pexels-photo-346751.jpeg',
    description: 'Klassískir, léttir og þægilegir sumar skór.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '1',
    name: 'Hlýr loðpels',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857348/pexels-photo-29857348.jpeg',
    description: 'Hlýlegur og glæsilegur pels fyrir vetrarveður.',
    subcategory: 'yfirhafnir',
  ),

  Product(
    id: '2',
    name: 'Fínn og hlýr jakki',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/842811/pexels-photo-842811.jpeg',
    description: 'Stílhreint útlit fyrir veislurnar.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Fínir leðurskór',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg',
    description: 'Vandaðir skór fyrir hversdags og formleg tilefni.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Létt peysa',
    color: 'Svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/845434/pexels-photo-845434.jpeg',
    description: 'Þægileg og flott fyrir daglegt líf.',
    subcategory: 'peysur',
  ),
  Product(
    id: '2',
    name: 'Töff hettupeysa',
    color: 'gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    description: 'Sterkur litur sem setur svip á daginn.',
    subcategory: 'peysur',
  ),
  Product(
    id: '2',
    name: 'Þægilegir strigaskór',
    color: 'appelsínugulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1306248/pexels-photo-1306248.jpeg',
    description: 'Frjálslegir og eftirtektarverðir skór.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Slim fit gallabuxur',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/878358/pexels-photo-878358.jpeg',
    description: 'Unglegur stíll fyrir hversdagsnotkun.',
    subcategory: 'buxur',
  ),
  Product(
    id: '2',
    name: 'Þröngar gallabuxur',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1018911/pexels-photo-1018911.jpeg',
    description: 'Unglegur stíll fyrir hversdagsnotkun.',
    subcategory: 'buxur',
  ),
  Product(
    id: '2',
    name: 'Þægileg skyrta',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg',
    description: 'Sígild skyrta sem passar við jakkaföt eða gallabuxur.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '2',
    name: 'Jakkafata jakki',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/450212/pexels-photo-450212.jpeg',
    description: 'Fínlegur klæðnaður fyrir formleg tilefni.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Adidas sport jakki',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1192601/pexels-photo-1192601.jpeg',
    description: 'Sportlegur jakki sem hentar vel í hreyfingu eða hversdagsleikann.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Hvít jakkaföt',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2709563/pexels-photo-2709563.jpeg',
    description: 'Fágað útlit fyrir sérstök tilefni.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Köflótt skyrta',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6765066/pexels-photo-6765066.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Flott í samsetningu með jakkafötum.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '2',
    name: 'Hringlótt sólgleraugu',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg',
    description: 'Léttur sumarsvipur.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'létt hettupeysa',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/634785/pexels-photo-634785.jpeg',
    description: 'Hentar vel fyrir ævintýraferðir og tískuljósmyndun;).',
    subcategory: 'peysur',
  ),
  Product(
    id: '2',
    name: 'Nike strigaskór',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1813947/pexels-photo-1813947.jpeg',
    description: 'Mjög vinsælir og þægilegir strigaskór.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Derhúfa',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/845457/pexels-photo-845457.jpeg',
    description: 'Hentugt fyrir sumarið.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Sólgleraugu',
    color: 'silfur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1078851/pexels-photo-1078851.jpeg',
    description: 'Klassískt útlit með blátintu gleri.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Gallabuxur',
    color: 'blár/hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/936023/pexels-photo-936023.jpeg',
    description: 'Rifnar, ekta tísku, gallabuxur.',
    subcategory: 'buxur',
  ),
  Product(
    id: '2',
    name: 'Loðfelds jakki',
    color: 'svartur/hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29863525/pexels-photo-29863525.jpeg',
    description: 'Áberandi feldur sem grípur alla athygli.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Loðin hettupeysa',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29852347/pexels-photo-29852347.jpeg',
    description: 'Konan sleppir þér ekki í þessu. Mjög kósý.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Sólgleraugu',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29822696/pexels-photo-29822696.jpeg',
    description: 'Svalt útlit.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Leðurjakki',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6037685/pexels-photo-6037685.jpeg',
    description: 'Stílhreinn og hlýr leður jakki fyrir hvaða tilefni sem er.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Dúnúlpur',
    color: 'grænn, grár, hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/7026411/pexels-photo-7026411.jpeg',
    description: 'Þykkar og hlýjar síðúlpur fyrir veturinn.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Galla jakki',
    color: 'blár/brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/14970274/pexels-photo-14970274.jpeg',
    description: 'Fóðraður galla jakki í bóndastörfin.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Kuldaskór',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/243917/pexels-photo-243917.jpeg',
    description: 'Sterkir skór sem henta vel í snjóinn en líka hversdagsleikan.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '2',
    name: 'Cargo buxur',
    color: 'grænn/svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/26987457/pexels-photo-26987457.jpeg',
    description: 'Taktikal útlit með sterka teygju, tilvalið í vinnuna.',
    subcategory: 'buxur',
  ),
  Product(
    id: '2',
    name: 'Frakki',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/5264736/pexels-photo-5264736.jpeg',
    description: 'Léttur og fínn frakki fyrir djammið',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'trefill',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/375880/pexels-photo-375880.jpeg',
    description: 'þykkur og hlýr bómullar trefill með fallegu mynstri.',
    subcategory: 'peysur',
  ),
  Product(
    id: '2',
    name: 'Hettupeysa',
    color: 'grænn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2144383/pexels-photo-2144383.jpeg',
    description: 'Óformleg, notaleg flík fyrir skólan.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'frakki',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6667782/pexels-photo-6667782.jpeg',
    description: 'Einföld og hlý kápa fyrir snjóinn .',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Lambhúshetta',
    color: 'marglit',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/10664875/pexels-photo-10664875.jpeg',
    description: 'Prjónuð skíðahúfa.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '2',
    name: 'Jólapeysa',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6517911/pexels-photo-6517911.jpeg',
    description: 'Tilvalin fyrir hátíðina.',
    subcategory: 'peysur',
  ),
  Product(
    id: '2',
    name: 'Leðurvesti',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/7955547/pexels-photo-7955547.jpeg',
    description: 'Töff útlit.',
    subcategory: 'fylgihlutir',
  ),


  Product(
    id: '3',
    name: 'Fínni platform skór',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857177/pexels-photo-29857177.jpeg',
    description: 'Fallegir skór sem passa við flest fín föt.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Eyrnaskjól',
    color: 'bleikur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29822083/pexels-photo-29822083.jpeg',
    description: 'Hlý eyrnaskjól fyrir vetrarveðrið.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Krúttlegur gallakjóll',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857626/pexels-photo-29857626.jpeg',
    description: 'Sætur kjóll sem hentar leik og hlátri.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '3',
    name: 'Hlý kápa',
    color: 'grænn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857628/pexels-photo-29857628.jpeg',
    description: 'Falleg og hlý vetrar kápa.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '3',
    name: 'Þægilegar gallabuxur',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857624/pexels-photo-29857624.jpeg',
    description: 'þægilegar víðar gallabuxur.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Gallabuxur',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/236215/pexels-photo-236215.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Töff gallastíll fyrir allan aldur.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Fín stígvel',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857622/pexels-photo-29857622.jpeg',
    description: 'Falleg og hlý stígvel.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '3',
    name: 'Stuttermabolur',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/4711735/pexels-photo-4711735.jpeg',
    description: 'Stílhrein fatnaður.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Langermakjóll með mittisbandi',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/4714773/pexels-photo-4714773.jpeg',
    description: 'Auðveldur til leikja og útivistar.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '3',
    name: 'Langerma kjóll með mynstri',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/7055295/pexels-photo-7055295.jpeg',
    description: 'Þægilegur í allskyns hreyfingu.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '3',
    name: 'Langermabolur með blómi',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6201971/pexels-photo-6201971.jpeg',
    description: 'Ljúfur og frjáls stíll.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Heilgalli',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6616173/pexels-photo-6616173.jpeg',
    description: 'Mjög vinsæll kósý galli.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Kjóll',
    color: 'bleikur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/8384996/pexels-photo-8384996.jpeg',
    description: 'Fullkomið fyrir afmæli eða partý.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '3',
    name: 'Heilgalli',
    color: 'grænn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/8141976/pexels-photo-8141976.jpeg',
    description: 'Skemmtileg flík fyrir öll tilefni.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Gallajakki',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29822084/pexels-photo-29822084.jpeg',
    description: 'Stílhreinn jakki sem virkar með flest öllu.',
    subcategory: 'yfirhafnir',
  ),
  Product(
    id: '3',
    name: 'Gallabuxur',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29822084/pexels-photo-29822084.jpeg',
    description: 'Víðar og þægilegar.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Kjóll',
    color: 'svartur/hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/933186/pexels-photo-933186.jpeg',
    description: 'Krúttlegur köflóttur kjóll inní sumarið.',
    subcategory: 'kjólar',
  ),
  Product(
    id: '3',
    name: 'strigaskór',
    color: 'Hvítur, bleikur, grænn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/10557069/pexels-photo-10557069.jpeg',
    description: 'Skemmtilegir litríkir skór.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Peysa',
    color: 'Hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/258303/pexels-photo-258303.jpeg',
    description: 'Hlý og mjúk peysa með kisum framan á. Tilvalið í skólann.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Heilgalli',
    color: 'Gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/6823110/pexels-photo-6823110.jpeg',
    description: 'Gulur bómullar heilgalli fyrir þau yngstu.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Bolur',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29863725/pexels-photo-29863725.jpeg',
    description: 'Þykkur og vandaður bolur með ápressað mynstur.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Loðpeysa',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29863250/pexels-photo-29863250.jpeg',
    description: 'Mjúk og hlý vetrarpeysa',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Hálfrenndur bolur',
    color: 'svartur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857634/pexels-photo-29857634.jpeg',
    description: 'Sætur fatnaður sem gleður alla í kring.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Skyrta',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/29857631/pexels-photo-29857631.jpeg',
    description: 'Skemmtileg blóma skreytt skyrta fyrir útlandaferðina.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Peysa',
    color: 'grænn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/5560026/pexels-photo-5560026.jpeg',
    description: 'Notaleg í skólann.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Peysa með mynstri',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/3965553/pexels-photo-3965553.jpeg',
    description: 'Mjúkt og hentugt fyrir haustveður.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Krúttleg skyrta',
    color: 'grár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/5859804/pexels-photo-5859804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Smekklegt og þægilegt, hentar leik og ról.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Stígvel',
    color: 'gulur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/2387702/pexels-photo-2387702.jpeg',
    description: 'Gleði og fjör í vatnsheldum skóm.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Stutterma skyrta',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1068209/pexels-photo-1068209.jpeg',
    description: 'Klæðnaður sem hentar leik og kátínu.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Gallasmekkbuxur',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/4715312/pexels-photo-4715312.jpeg',
    description: 'Þægilegar hversdagsbuxur.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Stuttermaskyrta',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/969373/pexels-photo-969373.jpeg',
    description: 'Hreinleg og klassísk skyrta.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Stuttermabolur',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/13198517/pexels-photo-13198517.jpeg',
    description: 'Tilvalið fyrir skólann.',
    subcategory: 'peysur',
  ),
  Product(
    id: '3',
    name: 'Andlit málað',
    color: 'ljós blár og hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1650281/pexels-photo-1650281.jpeg',
    description: 'Litagleði og krúttlegt útlit fyrir börn.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Skyrta',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/1620812/pexels-photo-1620812.jpeg',
    description: 'Skemtileg skyrta til að breyta til.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Skyrta',
    color: 'blár',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/3121075/pexels-photo-3121075.jpeg',
    description: 'Einföld og fín skyrta.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Rifnar allabuxur',
    color: 'Hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/25158809/pexels-photo-25158809.jpeg',
    description: 'Flottar buxur fyrir töffarana.',
    subcategory: 'buxur',
  ),
  Product(
    id: '3',
    name: 'Köflótt skyrta',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/25158809/pexels-photo-25158809.jpeg',
    description: 'Hentar í öll tilefni.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Leður skór',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/25158812/pexels-photo-25158812.jpeg',
    description: 'Fínni skór fyrir ýmis tilefni.',
    subcategory: 'fylgihlutir',
  ),
  Product(
    id: '3',
    name: 'Skyrta',
    color: 'hvítur',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/25158812/pexels-photo-25158812.jpeg',
    description: 'Þægileg og flott "oversize" skyrta.',
    subcategory: 'skyrtur',
  ),
  Product(
    id: '3',
    name: 'Bolur með mynstri',
    color: 'brúnn',
    price: 100,
    imageUrl: 'https://images.pexels.com/photos/25158801/pexels-photo-25158801.jpeg',
    description: 'Ferskur stíll með skemmtilega mynd.',
    subcategory: 'peysur',
  ),
];
